### ISSUE TITLE
diffsel error: non matching number of taxa

### ISSUE THREAD

**Issue by NatJWalker-Hale** [vlanore/diffsel#2]
I'm having trouble getting diffsel to parse a tree of 198 sequences. It was produced by IQ-TREE and I subsequently processed the branch labeling in R using ape. When I run diffsel, I receive the error: 

```
error : non matching number of taxa : 196	198
some taxa in the dataset are not present in the tree
```

I've attached the tree, with two random branches set to 1 and the rest to 0. Could you please help me figure out why this newick and alignment isn't being successfully parsed? 

Thanks in advance, 

Nathanael 

[test.phy.txt](https://github.com/vlanore/diffsel/files/3385749/test.phy.txt)
[test.tre.txt](https://github.com/vlanore/diffsel/files/3385750/test.tre.txt)

**Comment by vlanore** [comment]
Hello,

Sorry for the delay.
I just took some time to look at your problem and it seems that two taxon names are misspelled in your alignement: `Cactaceae_Hylocereus_lemairei_polyrhizus_15461` and `Chenopodiaceae_Chenopodium_giganteum_Chenopodium_amaranticolor_14731`.
Both have an `=` instead of a `_` in their name in the alignment but not in the tree.

To fix this, just replace all `=` with `_` in your alignment. With this fix, it works on my side.

**Comment by NatJWalker-Hale** [comment]
Thanks, that fixed it!

**Comment by vlanore** [comment]
Glad I could help!
Marking this issue as closed.
